/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-05-29 07:39:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.fashionstore.model.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("com.fashionstore.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    User user = (User) session.getAttribute("user");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>FashionStore — Curated Style</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/home.css?v=2\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- ── Nav ── -->\n");
      out.write("<nav class=\"top-nav\">\n");
      out.write("  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" class=\"nav-logo\">FASHION<span>.</span></a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\">Shop</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?categoryId=1\">Men</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?categoryId=2\">Women</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?categoryId=4\">Kids</a></li>\n");
      out.write("    ");
 if (user != null) { 
      out.write("\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order?action=myOrders\">Orders</a></li>\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart\">Cart</a></li>\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=profile\">");
      out.print( user.getName().split(" ")[0] );
      out.write("</a></li>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=login\">Sign in</a></li>\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=register\" class=\"nav-register\">Register</a></li>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<!-- ── Hero ── -->\n");
      out.write("<section class=\"hero\">\n");
      out.write("  <div class=\"hero-inner\">\n");
      out.write("    <p class=\"hero-eyebrow\">New Collection &nbsp;·&nbsp; 2026</p>\n");
      out.write("    <h1 class=\"hero-title\">\n");
      out.write("      Dress for<br>the life you<br><span>want.</span>\n");
      out.write("    </h1>\n");
      out.write("    <p class=\"hero-sub\">\n");
      out.write("      Curated fashion for men and women.<br>\n");
      out.write("      Premium quality, timeless style.\n");
      out.write("    </p>\n");
      out.write("    <div class=\"hero-actions\">\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"btn-primary\">\n");
      out.write("        Shop Collection\n");
      out.write("      </a>\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?categoryId=2\" class=\"btn-ghost\">\n");
      out.write("        Women's Edit\n");
      out.write("      </a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Decorative grid lines -->\n");
      out.write("  <div class=\"hero-grid\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"grid-line\"></div>\n");
      out.write("    <div class=\"grid-line\"></div>\n");
      out.write("    <div class=\"grid-line\"></div>\n");
      out.write("    <div class=\"grid-line\"></div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Scroll indicator -->\n");
      out.write("  <div class=\"scroll-hint\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"scroll-line\"></div>\n");
      out.write("    <span>Scroll</span>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- ── Category Split ── -->\n");
      out.write("<section class=\"category-split\">\n");
      out.write("\n");
      out.write("  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?categoryId=1\" class=\"cat-panel\">\n");
      out.write("    <div class=\"cat-bg cat-bg--men\"></div>\n");
      out.write("    <div class=\"cat-content\">\n");
      out.write("      <p class=\"cat-label\">Men</p>\n");
      out.write("      <h2 class=\"cat-title\">Sharp.<br>Refined.</h2>\n");
      out.write("      <span class=\"cat-link\">Explore Men's →</span>\n");
      out.write("    </div>\n");
      out.write("  </a>\n");
      out.write("\n");
      out.write("  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?categoryId=2\" class=\"cat-panel\">\n");
      out.write("    <div class=\"cat-bg cat-bg--women\"></div>\n");
      out.write("    <div class=\"cat-content\">\n");
      out.write("      <p class=\"cat-label\">Women</p>\n");
      out.write("      <h2 class=\"cat-title\">Bold.<br>Effortless.</h2>\n");
      out.write("      <span class=\"cat-link\">Explore Women's →</span>\n");
      out.write("    </div>\n");
      out.write("  </a>\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- ── Value Props ── -->\n");
      out.write("<section class=\"props-section\">\n");
      out.write("  <div class=\"props-grid\">\n");
      out.write("    <div class=\"prop-item\">\n");
      out.write("      <div class=\"prop-icon\">&#9632;</div>\n");
      out.write("      <h3 class=\"prop-title\">Premium Quality</h3>\n");
      out.write("      <p class=\"prop-desc\">Every piece is selected for craftsmanship, fit, and longevity.</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"prop-item\">\n");
      out.write("      <div class=\"prop-icon\">&#9632;</div>\n");
      out.write("      <h3 class=\"prop-title\">Free Delivery</h3>\n");
      out.write("      <p class=\"prop-desc\">Complimentary shipping on all orders above ₹999.</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"prop-item\">\n");
      out.write("      <div class=\"prop-icon\">&#9632;</div>\n");
      out.write("      <h3 class=\"prop-title\">Easy Returns</h3>\n");
      out.write("      <p class=\"prop-desc\">Not the right fit? Return within 30 days, no questions asked.</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"prop-item\">\n");
      out.write("      <div class=\"prop-icon\">&#9632;</div>\n");
      out.write("      <h3 class=\"prop-title\">Secure Checkout</h3>\n");
      out.write("      <p class=\"prop-desc\">Your data and payments are always safe with us.</p>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- ── CTA Banner ── -->\n");
      out.write("<section class=\"cta-banner\">\n");
      out.write("  <div class=\"cta-inner\">\n");
      out.write("    <p class=\"cta-eyebrow\">Limited Time</p>\n");
      out.write("    <h2 class=\"cta-title\">Free delivery on orders above ₹999</h2>\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"btn-primary\">\n");
      out.write("      Shop Now\n");
      out.write("    </a>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- ── Footer ── -->\n");
      out.write("<footer class=\"site-footer\">\n");
      out.write("  <div class=\"footer-top\">\n");
      out.write("    <div class=\"footer-brand\">\n");
      out.write("      <div class=\"footer-logo\">FASHION<span>.</span></div>\n");
      out.write("      <p class=\"footer-tagline\">Curated Style &nbsp;·&nbsp; Premium Quality</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"footer-links\">\n");
      out.write("      <div class=\"footer-col\">\n");
      out.write("        <p class=\"footer-col-title\">Shop</p>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\">All Products</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?categoryId=1\">Men</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?categoryId=2\">Women</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?categoryId=4\">Kids</a>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"footer-col\">\n");
      out.write("        <p class=\"footer-col-title\">Account</p>\n");
      out.write("        ");
 if (user != null) { 
      out.write("\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=profile\">My Profile</a>\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order?action=myOrders\">My Orders</a>\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=logout\">Sign Out</a>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=login\">Sign In</a>\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=register\">Register</a>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"footer-bottom\">\n");
      out.write("    <p>&copy; 2026 FashionStore. All rights reserved.</p>\n");
      out.write("  </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  // Scroll indicator fade\n");
      out.write("  window.addEventListener('scroll', () => {\n");
      out.write("    const hint = document.querySelector('.scroll-hint');\n");
      out.write("    if (hint) hint.style.opacity = window.scrollY > 80 ? '0' : '1';\n");
      out.write("  });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
