/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-05-29 05:51:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.fashionstore.model.User;
import com.fashionstore.model.CartItemView;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.fashionstore.model.CartItemView");
    _jspx_imports_classes.add("com.fashionstore.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    List<CartItemView> cartItems = (List<CartItemView>) request.getAttribute("cartItems");
    double totalAmount = request.getAttribute("totalAmount") != null ? (double) request.getAttribute("totalAmount") : 0;
    int cartCount = request.getAttribute("cartCount") != null ? (int) request.getAttribute("cartCount") : 0;
    User user = (User) session.getAttribute("user");
    boolean isEmpty = cartItems == null || cartItems.isEmpty();
    double deliveryCharge = totalAmount >= 999 ? 0 : 99;
    double grandTotal = totalAmount + deliveryCharge;
    boolean added = "true".equals(request.getParameter("added"));
    boolean orderFailed = "orderFailed".equals(request.getParameter("error"));

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>My Cart — FashionStore</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/cart.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/toast.css\">\n");
      out.write("  ");
 if (added) { 
      out.write("\n");
      out.write("    <meta name=\"toast-message\" content=\"Item added to your cart!\" data-type=\"success\" data-sub=\"Review your cart before checkout\">\n");
      out.write("  ");
 } 
      out.write('\n');
      out.write(' ');
      out.write(' ');
 if (orderFailed) { 
      out.write("\n");
      out.write("    <meta name=\"toast-message\" content=\"Failed to place order\" data-type=\"error\" data-sub=\"Please try again or contact support\">\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"top-nav\">\n");
      out.write("  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"nav-logo\">FASHION<span>.</span></a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\">Shop</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=profile\">");
      out.print( user.getName().split(" ")[0] );
      out.write("</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order?action=myOrders\">Orders</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart\" class=\"nav-cart active\">Cart");
 if (cartCount > 0) { 
      out.write("<span class=\"nav-cart-badge\">");
      out.print( cartCount );
      out.write("</span>");
 } 
      out.write("</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=logout\">Sign out</a></li>\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"page-body\">\n");
      out.write("  <div class=\"page-header\">\n");
      out.write("    <p class=\"page-eyebrow\">Shopping</p>\n");
      out.write("    <h1 class=\"page-title\">My Cart");
 if (!isEmpty) { 
      out.write(" <span style=\"font-size:20px;color:var(--muted);font-family:'Barlow',sans-serif;font-weight:300;\">(");
      out.print( cartCount );
      out.write(' ');
      out.print( cartCount == 1 ? "item" : "items" );
      out.write(")</span>");
 } 
      out.write("</h1>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"cart-layout\">\n");
      out.write("    ");
 if (!isEmpty) { 
      out.write("\n");
      out.write("      <div class=\"cart-items-wrap\">\n");
      out.write("        ");
 for (CartItemView view : cartItems) { 
      out.write("\n");
      out.write("          <div class=\"cart-item\">\n");
      out.write("            <div class=\"cart-item-img-wrap\">\n");
      out.write("              ");
 if (view.getProduct().getImageUrl() != null && !view.getProduct().getImageUrl().isEmpty()) { 
      out.write("\n");
      out.write("                <img class=\"cart-item-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.print( view.getProduct().getImageUrl() );
      out.write("\" alt=\"");
      out.print( view.getProduct().getName() );
      out.write("\">\n");
      out.write("              ");
 } else { 
      out.write("\n");
      out.write("                <div class=\"cart-item-img-placeholder\">&#9900;</div>\n");
      out.write("              ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div class=\"cart-item-details\">\n");
      out.write("              <p class=\"cart-item-category\">");
      out.print( view.getProduct().getCategoryId() == 1 ? "Men" : "Women" );
      out.write("</p>\n");
      out.write("              <h3 class=\"cart-item-name\">");
      out.print( view.getProduct().getName() );
      out.write("</h3>\n");
      out.write("              <div class=\"cart-item-meta\">\n");
      out.write("                <span>Size: ");
      out.print( view.getSize() );
      out.write("</span>\n");
      out.write("                <span>&#8377;");
      out.print( String.format("%.0f", view.getProduct().getPrice()) );
      out.write(" each</span>\n");
      out.write("              </div>\n");
      out.write("              <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart\" method=\"post\" id=\"qtyForm_");
      out.print( view.getItem().getId() );
      out.write("\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"update\">\n");
      out.write("                <input type=\"hidden\" name=\"cartItemId\" value=\"");
      out.print( view.getItem().getId() );
      out.write("\">\n");
      out.write("                <input type=\"hidden\" name=\"quantity\" id=\"qtyHidden_");
      out.print( view.getItem().getId() );
      out.write("\" value=\"");
      out.print( view.getItem().getQuantity() );
      out.write("\">\n");
      out.write("              </form>\n");
      out.write("              <div class=\"qty-control\">\n");
      out.write("                <button type=\"button\" class=\"qty-btn\" onclick=\"changeQty(");
      out.print( view.getItem().getId() );
      out.write(", -1)\">&#8722;</button>\n");
      out.write("                <div class=\"qty-display\" id=\"qtyDisplay_");
      out.print( view.getItem().getId() );
      out.write('"');
      out.write('>');
      out.print( view.getItem().getQuantity() );
      out.write("</div>\n");
      out.write("                <button type=\"button\" class=\"qty-btn\" onclick=\"changeQty(");
      out.print( view.getItem().getId() );
      out.write(", 1)\">&#43;</button>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"cart-item-actions\">\n");
      out.write("              <p class=\"cart-item-total\">&#8377;");
      out.print( String.format("%.0f", view.getItemTotal()) );
      out.write("</p>\n");
      out.write("              <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart\" method=\"post\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"remove\">\n");
      out.write("                <input type=\"hidden\" name=\"cartItemId\" value=\"");
      out.print( view.getItem().getId() );
      out.write("\">\n");
      out.write("                <button type=\"submit\" class=\"btn-remove\"\n");
      out.write("                        onclick=\"Toast.info('Item removed from cart')\">Remove</button>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"order-summary\">\n");
      out.write("        <p class=\"summary-title\">Order Summary</p>\n");
      out.write("        <div class=\"summary-row\"><span>Subtotal (");
      out.print( cartCount );
      out.write(" items)</span><span>&#8377;");
      out.print( String.format("%.0f", totalAmount) );
      out.write("</span></div>\n");
      out.write("        <div class=\"summary-row\">\n");
      out.write("          <span>Delivery</span>\n");
      out.write("          <span>");
 if (deliveryCharge == 0) { 
      out.write("<span style=\"color:var(--success);\">Free</span>");
 } else { 
      out.write("&#8377;");
      out.print( String.format("%.0f", deliveryCharge) );
 } 
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("        ");
 if (deliveryCharge > 0) { 
      out.write("\n");
      out.write("          <p style=\"font-size:11px;color:var(--muted);margin-bottom:4px;\">Add &#8377;");
      out.print( String.format("%.0f", 999 - totalAmount) );
      out.write(" more for free delivery</p>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <div class=\"summary-row total\"><span>Total</span><span class=\"summary-val\">&#8377;");
      out.print( String.format("%.0f", grandTotal) );
      out.write("</span></div>\n");
      out.write("        <p class=\"summary-note\">Taxes included. Free delivery above ₹999.</p>\n");
      out.write("        <button type=\"button\" class=\"btn-checkout\" onclick=\"showConfirmModal()\">Proceed to Checkout</button>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"btn-continue\">Continue Shopping</a>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("      <div class=\"empty-cart\">\n");
      out.write("        <div class=\"empty-cart-icon\">\n");
      out.write("          <svg width=\"80\" height=\"80\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.8\">\n");
      out.write("            <path d=\"M6 2L3 6v14a2 2 0 002 2h14a2 2 0 002-2V6l-3-4z\"/>\n");
      out.write("            <line x1=\"3\" y1=\"6\" x2=\"21\" y2=\"6\"/>\n");
      out.write("            <path d=\"M16 10a4 4 0 01-8 0\"/>\n");
      out.write("          </svg>\n");
      out.write("        </div>\n");
      out.write("        <h2>Your cart is empty</h2>\n");
      out.write("        <p>Browse our collection and add something you love.</p>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\">Browse Collection</a>\n");
      out.write("      </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <footer class=\"site-footer\">\n");
      out.write("    <div class=\"footer-logo\">FASHION<span>.</span></div>\n");
      out.write("    <p class=\"footer-note\">&copy; 2025 FashionStore. All rights reserved.</p>\n");
      out.write("  </footer>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- ── Confirmation Modal ── -->\n");
      out.write("<div id=\"confirmModal\" style=\"\n");
      out.write("  display:none;\n");
      out.write("  position:fixed;\n");
      out.write("  inset:0;\n");
      out.write("  z-index:9999;\n");
      out.write("  background:rgba(0,0,0,0.75);\n");
      out.write("  backdrop-filter:blur(4px);\n");
      out.write("  align-items:center;\n");
      out.write("  justify-content:center;\n");
      out.write("\">\n");
      out.write("  <div style=\"\n");
      out.write("    background:#111;\n");
      out.write("    border:1px solid #2e2e2e;\n");
      out.write("    border-radius:4px;\n");
      out.write("    padding:40px;\n");
      out.write("    max-width:420px;\n");
      out.write("    width:90%;\n");
      out.write("    position:relative;\n");
      out.write("    box-shadow:0 24px 64px rgba(0,0,0,0.8);\n");
      out.write("  \">\n");
      out.write("    <!-- Gold accent top bar -->\n");
      out.write("    <div style=\"position:absolute;top:0;left:0;right:0;height:2px;background:#c9a84c;border-radius:4px 4px 0 0;\"></div>\n");
      out.write("\n");
      out.write("    <!-- Icon -->\n");
      out.write("    <div style=\"text-align:center;margin-bottom:20px;\">\n");
      out.write("      <div style=\"\n");
      out.write("        width:56px;height:56px;\n");
      out.write("        background:rgba(201,168,76,0.1);\n");
      out.write("        border:1px solid #8a6f2e;\n");
      out.write("        border-radius:50%;\n");
      out.write("        display:inline-flex;\n");
      out.write("        align-items:center;\n");
      out.write("        justify-content:center;\n");
      out.write("        font-size:22px;\n");
      out.write("      \">&#128722;</div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Title -->\n");
      out.write("    <h2 style=\"\n");
      out.write("      font-family:'Playfair Display',serif;\n");
      out.write("      font-size:24px;\n");
      out.write("      font-weight:700;\n");
      out.write("      color:#f5f5f0;\n");
      out.write("      text-align:center;\n");
      out.write("      margin-bottom:8px;\n");
      out.write("      letter-spacing:-0.5px;\n");
      out.write("    \">Confirm Your Order</h2>\n");
      out.write("\n");
      out.write("    <p style=\"\n");
      out.write("      font-size:13px;\n");
      out.write("      color:#777;\n");
      out.write("      text-align:center;\n");
      out.write("      margin-bottom:24px;\n");
      out.write("      line-height:1.6;\n");
      out.write("    \">You are about to place an order for</p>\n");
      out.write("\n");
      out.write("    <!-- Amount -->\n");
      out.write("    <div style=\"\n");
      out.write("      background:#1a1a1a;\n");
      out.write("      border:1px solid #2e2e2e;\n");
      out.write("      border-radius:4px;\n");
      out.write("      padding:16px 24px;\n");
      out.write("      display:flex;\n");
      out.write("      justify-content:space-between;\n");
      out.write("      align-items:center;\n");
      out.write("      margin-bottom:8px;\n");
      out.write("    \">\n");
      out.write("      <span style=\"font-size:12px;letter-spacing:1px;color:#777;text-transform:uppercase;\">Total Amount</span>\n");
      out.write("      <span style=\"font-family:'Playfair Display',serif;font-size:22px;font-weight:700;color:#c9a84c;\" id=\"modalTotal\"></span>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div style=\"\n");
      out.write("      display:flex;\n");
      out.write("      justify-content:space-between;\n");
      out.write("      align-items:center;\n");
      out.write("      margin-bottom:28px;\n");
      out.write("      padding:0 4px;\n");
      out.write("    \">\n");
      out.write("      <span style=\"font-size:11px;color:#555;\">Delivery to ");
      out.print( user != null ? user.getAddressLine() != null && !user.getAddressLine().isEmpty() ? user.getAddressLine() : user.getCity() != null ? user.getCity() : "your address" : "your address" );
      out.write("</span>\n");
      out.write("      <span style=\"font-size:11px;color:");
      out.print( deliveryCharge == 0 ? "#2ecc71" : "#c9a84c" );
      out.write(";\">\n");
      out.write("        Delivery: ");
      out.print( deliveryCharge == 0 ? "Free" : "₹" + String.format("%.0f", deliveryCharge) );
      out.write("\n");
      out.write("      </span>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Buttons -->\n");
      out.write("    <div style=\"display:flex;gap:12px;\">\n");
      out.write("      <button onclick=\"hideConfirmModal()\" style=\"\n");
      out.write("        flex:1;\n");
      out.write("        padding:13px;\n");
      out.write("        background:transparent;\n");
      out.write("        color:#999;\n");
      out.write("        border:1px solid #2e2e2e;\n");
      out.write("        border-radius:2px;\n");
      out.write("        font-family:'Barlow',sans-serif;\n");
      out.write("        font-size:11px;\n");
      out.write("        font-weight:500;\n");
      out.write("        letter-spacing:2px;\n");
      out.write("        text-transform:uppercase;\n");
      out.write("        cursor:pointer;\n");
      out.write("        transition:border-color 0.2s,color 0.2s;\n");
      out.write("      \" onmouseover=\"this.style.borderColor='#c9a84c';this.style.color='#c9a84c'\"\n");
      out.write("         onmouseout=\"this.style.borderColor='#2e2e2e';this.style.color='#999'\">\n");
      out.write("        Cancel\n");
      out.write("      </button>\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order?action=placeOrder\" style=\"\n");
      out.write("        flex:1;\n");
      out.write("        padding:13px;\n");
      out.write("        background:#c9a84c;\n");
      out.write("        color:#0a0a0a;\n");
      out.write("        border:none;\n");
      out.write("        border-radius:2px;\n");
      out.write("        font-family:'Barlow',sans-serif;\n");
      out.write("        font-size:11px;\n");
      out.write("        font-weight:600;\n");
      out.write("        letter-spacing:2px;\n");
      out.write("        text-transform:uppercase;\n");
      out.write("        cursor:pointer;\n");
      out.write("        text-align:center;\n");
      out.write("        text-decoration:none;\n");
      out.write("        display:flex;\n");
      out.write("        align-items:center;\n");
      out.write("        justify-content:center;\n");
      out.write("        transition:background 0.2s;\n");
      out.write("      \" onmouseover=\"this.style.background='#d4b05a'\"\n");
      out.write("         onmouseout=\"this.style.background='#c9a84c'\">\n");
      out.write("        Confirm Order\n");
      out.write("      </a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Close X -->\n");
      out.write("    <button onclick=\"hideConfirmModal()\" style=\"\n");
      out.write("      position:absolute;\n");
      out.write("      top:16px;right:16px;\n");
      out.write("      background:transparent;\n");
      out.write("      border:none;\n");
      out.write("      color:#555;\n");
      out.write("      font-size:18px;\n");
      out.write("      cursor:pointer;\n");
      out.write("      line-height:1;\n");
      out.write("      transition:color 0.2s;\n");
      out.write("    \" onmouseover=\"this.style.color='#f5f5f0'\"\n");
      out.write("       onmouseout=\"this.style.color='#555'\">&#x2715;</button>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/toast.js\"></script>\n");
      out.write("<script>\n");
      out.write("  function changeQty(itemId, delta) {\n");
      out.write("    const display = document.getElementById('qtyDisplay_' + itemId);\n");
      out.write("    const hidden  = document.getElementById('qtyHidden_'  + itemId);\n");
      out.write("    const form    = document.getElementById('qtyForm_'    + itemId);\n");
      out.write("    let current = parseInt(display.textContent);\n");
      out.write("    let newVal  = current + delta;\n");
      out.write("    if (newVal < 1) newVal = 1;\n");
      out.write("    if (newVal > 10) newVal = 10;\n");
      out.write("    display.textContent = newVal;\n");
      out.write("    hidden.value = newVal;\n");
      out.write("    Toast.info('Quantity updated');\n");
      out.write("    setTimeout(() => form.submit(), 400);\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  function showConfirmModal() {\n");
      out.write("    // Get grand total from page\n");
      out.write("    const totalEl = document.querySelector('.summary-val');\n");
      out.write("    document.getElementById('modalTotal').textContent = totalEl ? totalEl.textContent : '';\n");
      out.write("    const modal = document.getElementById('confirmModal');\n");
      out.write("    modal.style.display = 'flex';\n");
      out.write("    // Prevent background scroll\n");
      out.write("    document.body.style.overflow = 'hidden';\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  function hideConfirmModal() {\n");
      out.write("    document.getElementById('confirmModal').style.display = 'none';\n");
      out.write("    document.body.style.overflow = '';\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  // Close on backdrop click\n");
      out.write("  document.getElementById('confirmModal').addEventListener('click', function(e) {\n");
      out.write("    if (e.target === this) hideConfirmModal();\n");
      out.write("  });\n");
      out.write("\n");
      out.write("  // Close on Escape key\n");
      out.write("  document.addEventListener('keydown', function(e) {\n");
      out.write("    if (e.key === 'Escape') hideConfirmModal();\n");
      out.write("  });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
