/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-05-29 05:51:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.text.SimpleDateFormat;
import com.fashionstore.model.Order;
import com.fashionstore.model.OrderItem;
import com.fashionstore.model.User;

public final class order_002ddetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(5);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.fashionstore.model.Order");
    _jspx_imports_classes.add("com.fashionstore.model.User");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.fashionstore.model.OrderItem");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Order order           = (Order) request.getAttribute("order");
    List<OrderItem> items = (List<OrderItem>) request.getAttribute("orderItems");
    User user             = (User) session.getAttribute("user");
    SimpleDateFormat sdf  = new SimpleDateFormat("dd MMM yyyy, hh:mm a");

    String status = order.getStatus().toUpperCase();

    // Timeline step states: 0=pending, 1=active, 2=done
    int placedState    = 0;
    int shippedState   = 0;
    int deliveredState = 0;

    if (status.equals("PLACED")) {
        placedState = 1;
    } else if (status.equals("SHIPPED")) {
        placedState    = 2;
        shippedState   = 1;
    } else if (status.equals("DELIVERED")) {
        placedState    = 2;
        shippedState   = 2;
        deliveredState = 1;
    } else if (status.equals("CANCELLED")) {
        placedState = 2; // show placed as done but cancelled
    }

    String statusClass = "status-placed";
    if (status.equals("SHIPPED"))    statusClass = "status-shipped";
    if (status.equals("DELIVERED"))  statusClass = "status-delivered";
    if (status.equals("CANCELLED"))  statusClass = "status-cancelled";

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Order #");
      out.print( order.getId() );
      out.write(" — FashionStore</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/order.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/toast.css\">\n");
      out.write("  <style>\n");
      out.write("\n");
      out.write("    /* ── ORDER TRACKING TIMELINE ─────────────── */\n");
      out.write("\n");
      out.write("    .tracking-section {\n");
      out.write("      max-width: 960px;\n");
      out.write("      margin: 0 auto;\n");
      out.write("      padding: 32px 48px 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .tracking-card {\n");
      out.write("      background: var(--coal);\n");
      out.write("      border: 1px solid var(--border);\n");
      out.write("      border-radius: 4px;\n");
      out.write("      padding: 32px 40px;\n");
      out.write("      margin-bottom: 24px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .tracking-title {\n");
      out.write("      font-size: 10px;\n");
      out.write("      letter-spacing: 3px;\n");
      out.write("      text-transform: uppercase;\n");
      out.write("      color: var(--muted);\n");
      out.write("      font-weight: 500;\n");
      out.write("      margin-bottom: 32px;\n");
      out.write("      padding-bottom: 16px;\n");
      out.write("      border-bottom: 1px solid var(--border);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .timeline {\n");
      out.write("      display: flex;\n");
      out.write("      align-items: flex-start;\n");
      out.write("      position: relative;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* connecting line */\n");
      out.write("    .timeline::before {\n");
      out.write("      content: '';\n");
      out.write("      position: absolute;\n");
      out.write("      top: 18px;\n");
      out.write("      left: calc(16.66% + 18px);\n");
      out.write("      right: calc(16.66% + 18px);\n");
      out.write("      height: 1px;\n");
      out.write("      background: var(--border);\n");
      out.write("      z-index: 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .timeline-step {\n");
      out.write("      flex: 1;\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: column;\n");
      out.write("      align-items: center;\n");
      out.write("      gap: 12px;\n");
      out.write("      position: relative;\n");
      out.write("      z-index: 1;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* dot */\n");
      out.write("    .step-dot {\n");
      out.write("      width: 36px;\n");
      out.write("      height: 36px;\n");
      out.write("      border-radius: 50%;\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("      justify-content: center;\n");
      out.write("      font-size: 14px;\n");
      out.write("      font-weight: 600;\n");
      out.write("      transition: all 0.3s ease;\n");
      out.write("      position: relative;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* pending */\n");
      out.write("    .step-dot.pending {\n");
      out.write("      background: var(--graphite);\n");
      out.write("      border: 1px solid var(--border);\n");
      out.write("      color: var(--muted);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* active — current status */\n");
      out.write("    .step-dot.active {\n");
      out.write("      background: var(--gold);\n");
      out.write("      border: 2px solid var(--gold);\n");
      out.write("      color: var(--black);\n");
      out.write("      box-shadow: 0 0 0 4px rgba(201,168,76,0.15);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* done — passed */\n");
      out.write("    .step-dot.done {\n");
      out.write("      background: var(--graphite);\n");
      out.write("      border: 1px solid var(--gold-dim);\n");
      out.write("      color: var(--gold);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* cancelled */\n");
      out.write("    .step-dot.cancelled {\n");
      out.write("      background: rgba(192,57,43,0.1);\n");
      out.write("      border: 1px solid var(--danger);\n");
      out.write("      color: var(--danger);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* connecting line fill for completed steps */\n");
      out.write("    .timeline-line {\n");
      out.write("      position: absolute;\n");
      out.write("      top: 18px;\n");
      out.write("      height: 1px;\n");
      out.write("      z-index: 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .timeline-line.done-line {\n");
      out.write("      background: var(--gold-dim);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .step-label {\n");
      out.write("      font-size: 11px;\n");
      out.write("      font-weight: 500;\n");
      out.write("      letter-spacing: 1px;\n");
      out.write("      text-transform: uppercase;\n");
      out.write("      text-align: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .step-label.pending   { color: var(--muted); }\n");
      out.write("    .step-label.active    { color: var(--gold); }\n");
      out.write("    .step-label.done      { color: var(--silver); }\n");
      out.write("    .step-label.cancelled { color: var(--danger); }\n");
      out.write("\n");
      out.write("    .step-date {\n");
      out.write("      font-size: 11px;\n");
      out.write("      color: var(--muted);\n");
      out.write("      text-align: center;\n");
      out.write("      letter-spacing: 0.3px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* cancelled banner */\n");
      out.write("    .cancelled-banner {\n");
      out.write("      background: rgba(192,57,43,0.08);\n");
      out.write("      border: 1px solid var(--danger);\n");
      out.write("      border-radius: 4px;\n");
      out.write("      padding: 14px 20px;\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("      gap: 10px;\n");
      out.write("      margin-bottom: 24px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .cancelled-banner-icon {\n");
      out.write("      color: var(--danger);\n");
      out.write("      font-size: 16px;\n");
      out.write("      flex-shrink: 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .cancelled-banner-text {\n");
      out.write("      font-size: 13px;\n");
      out.write("      color: #e57373;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* item image */\n");
      out.write("    .order-item-row {\n");
      out.write("      display: grid;\n");
      out.write("      grid-template-columns: 72px 1fr auto;\n");
      out.write("      gap: 16px;\n");
      out.write("      padding: 16px 0;\n");
      out.write("      border-bottom: 1px solid var(--border);\n");
      out.write("      align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .order-item-row:last-child { border-bottom: none; }\n");
      out.write("\n");
      out.write("    .order-item-img {\n");
      out.write("      width: 72px;\n");
      out.write("      height: 96px;\n");
      out.write("      object-fit: cover;\n");
      out.write("      object-position: top;\n");
      out.write("      background: var(--graphite);\n");
      out.write("      display: block;\n");
      out.write("      border-radius: 2px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .order-item-img-placeholder {\n");
      out.write("      width: 72px;\n");
      out.write("      height: 96px;\n");
      out.write("      background: var(--graphite);\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("      justify-content: center;\n");
      out.write("      color: var(--muted);\n");
      out.write("      font-size: 22px;\n");
      out.write("      border-radius: 2px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- ── Nav ── -->\n");
      out.write("<nav class=\"top-nav\">\n");
      out.write("  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"nav-logo\">FASHION<span>.</span></a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\">Shop</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=profile\">");
      out.print( user.getName().split(" ")[0] );
      out.write("</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order?action=myOrders\" class=\"active\">Orders</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart\">Cart</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=logout\">Sign out</a></li>\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"page-body\">\n");
      out.write("\n");
      out.write("  <!-- ── Breadcrumb ── -->\n");
      out.write("  <div class=\"breadcrumb\">\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order?action=myOrders\">My Orders</a>\n");
      out.write("    <span class=\"breadcrumb-sep\">&#8250;</span>\n");
      out.write("    <span class=\"breadcrumb-current\">Order #");
      out.print( order.getId() );
      out.write("</span>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- ── Flash messages ── -->\n");
      out.write("  ");
 if (request.getParameter("cancelled") != null) { 
      out.write("\n");
      out.write("    <div style=\"max-width:960px;margin:16px auto 0;padding:0 48px;\">\n");
      out.write("      <div style=\"background:rgba(46,204,113,0.08);border-left:3px solid #2ecc71;padding:12px 16px;font-size:13px;color:#66bb6a;border-radius:2px;\">\n");
      out.write("        &#10003; &nbsp;Order cancelled successfully.\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  ");
 } 
      out.write('\n');
      out.write(' ');
      out.write(' ');
 if ("true".equals(request.getParameter("cancelError"))) { 
      out.write("\n");
      out.write("    <div style=\"max-width:960px;margin:16px auto 0;padding:0 48px;\">\n");
      out.write("      <div style=\"background:rgba(192,57,43,0.1);border-left:3px solid #c0392b;padding:12px 16px;font-size:13px;color:#e57373;border-radius:2px;\">\n");
      out.write("        &#10005; &nbsp;This order cannot be cancelled. It may already be shipped or delivered.\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("  <!-- ── Tracking Timeline ── -->\n");
      out.write("  <div class=\"tracking-section\">\n");
      out.write("\n");
      out.write("    ");
 if (status.equals("CANCELLED")) { 
      out.write("\n");
      out.write("      <div class=\"cancelled-banner\">\n");
      out.write("        <span class=\"cancelled-banner-icon\">✕</span>\n");
      out.write("        <span class=\"cancelled-banner-text\">This order was cancelled.</span>\n");
      out.write("      </div>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"tracking-card\">\n");
      out.write("      <p class=\"tracking-title\">Order Status</p>\n");
      out.write("\n");
      out.write("      <div class=\"timeline\">\n");
      out.write("\n");
      out.write("        <!-- Step 1: Placed -->\n");
      out.write("        <div class=\"timeline-step\">\n");
      out.write("          <div class=\"step-dot ");
      out.print( placedState == 1 ? "active" : placedState == 2 ? "done" : "pending" );
      out.write("\">\n");
      out.write("            ");
      out.print( placedState == 2 ? "✓" : "1" );
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <span class=\"step-label ");
      out.print( placedState == 1 ? "active" : placedState == 2 ? "done" : "pending" );
      out.write("\">\n");
      out.write("            Order Placed\n");
      out.write("          </span>\n");
      out.write("          <span class=\"step-date\">");
      out.print( sdf.format(order.getOrderDate()) );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Step 2: Shipped -->\n");
      out.write("        <div class=\"timeline-step\">\n");
      out.write("          <div class=\"step-dot ");
      out.print( shippedState == 1 ? "active" : shippedState == 2 ? "done" : "pending" );
      out.write("\">\n");
      out.write("            ");
      out.print( shippedState == 2 ? "✓" : "2" );
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <span class=\"step-label ");
      out.print( shippedState == 1 ? "active" : shippedState == 2 ? "done" : "pending" );
      out.write("\">\n");
      out.write("            Shipped\n");
      out.write("          </span>\n");
      out.write("          <span class=\"step-date\">\n");
      out.write("            ");
      out.print( shippedState > 0 ? "In transit" : "Pending" );
      out.write("\n");
      out.write("          </span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Step 3: Delivered -->\n");
      out.write("        <div class=\"timeline-step\">\n");
      out.write("          <div class=\"step-dot ");
      out.print( deliveredState == 1 ? "active" : deliveredState == 2 ? "done" : "pending" );
      out.write("\">\n");
      out.write("            ");
      out.print( deliveredState == 2 ? "✓" : "3" );
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <span class=\"step-label ");
      out.print( deliveredState == 1 ? "active" : deliveredState == 2 ? "done" : "pending" );
      out.write("\">\n");
      out.write("            Delivered\n");
      out.write("          </span>\n");
      out.write("          <span class=\"step-date\">\n");
      out.write("            ");
      out.print( deliveredState > 0 ? "Delivered" : "Estimated 3-5 days" );
      out.write("\n");
      out.write("          </span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- ── Detail Grid ── -->\n");
      out.write("  <div class=\"detail-grid\">\n");
      out.write("\n");
      out.write("    <!-- Left: Items -->\n");
      out.write("    <div class=\"detail-card\">\n");
      out.write("      <p class=\"detail-card-title\">Order Items</p>\n");
      out.write("\n");
      out.write("      ");
 if (items != null && !items.isEmpty()) {
           for (OrderItem item : items) {
             String catName = item.getCategoryId() == 1 ? "Men" : "Women";
             String name    = item.getProductName() != null ? item.getProductName() : "Product #" + item.getProductId();
             String img     = item.getProductImage();
      
      out.write("\n");
      out.write("        <div class=\"order-item-row\">\n");
      out.write("          ");
 if (img != null && !img.isEmpty()) { 
      out.write("\n");
      out.write("            <img class=\"order-item-img\"\n");
      out.write("                 src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.print( img );
      out.write("\"\n");
      out.write("                 alt=\"");
      out.print( name );
      out.write("\">\n");
      out.write("          ");
 } else { 
      out.write("\n");
      out.write("            <div class=\"order-item-img-placeholder\">&#9900;</div>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("          <div>\n");
      out.write("            <p class=\"order-item-name\">");
      out.print( name );
      out.write("</p>\n");
      out.write("            <p class=\"order-item-meta\">\n");
      out.write("              ");
      out.print( catName );
      out.write(" &nbsp;·&nbsp;\n");
      out.write("              Qty: ");
      out.print( item.getQuantity() );
      out.write(" &nbsp;·&nbsp;\n");
      out.write("              &#8377;");
      out.print( String.format("%.0f", item.getPrice()) );
      out.write(" each\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("          <p class=\"order-item-price\">\n");
      out.write("            &#8377;");
      out.print( String.format("%.0f", item.getPrice() * item.getQuantity()) );
      out.write("\n");
      out.write("          </p>\n");
      out.write("        </div>\n");
      out.write("      ");
   }
         } else { 
      out.write("\n");
      out.write("        <p style=\"color:var(--muted);font-size:13px;\">No items found.</p>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Right: Summary -->\n");
      out.write("    <div class=\"detail-summary\">\n");
      out.write("\n");
      out.write("      <div class=\"summary-card\">\n");
      out.write("        <p class=\"summary-card-title\">Order Summary</p>\n");
      out.write("        <div class=\"summary-row\">\n");
      out.write("          <span>Order ID</span>\n");
      out.write("          <span>#");
      out.print( order.getId() );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"summary-row\">\n");
      out.write("          <span>Date</span>\n");
      out.write("          <span>");
      out.print( sdf.format(order.getOrderDate()) );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"summary-row\">\n");
      out.write("          <span>Status</span>\n");
      out.write("          <span class=\"order-status ");
      out.print( statusClass );
      out.write('"');
      out.write('>');
      out.print( order.getStatus() );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"summary-row total\">\n");
      out.write("          <span>Total</span>\n");
      out.write("          <span>&#8377;");
      out.print( String.format("%.0f", order.getTotalAmount()) );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"summary-card\">\n");
      out.write("        <p class=\"summary-card-title\">Delivery Address</p>\n");
      out.write("        <div class=\"info-row\">\n");
      out.write("          <span class=\"info-label\">Name</span>\n");
      out.write("          <span class=\"info-value\">");
      out.print( user.getName() );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("        ");
 if (user.getAddressLine() != null && !user.getAddressLine().isEmpty()) { 
      out.write("\n");
      out.write("          <div class=\"info-row\">\n");
      out.write("            <span class=\"info-label\">Address</span>\n");
      out.write("            <span class=\"info-value\">");
      out.print( user.getAddressLine() );
      out.write("</span>\n");
      out.write("          </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        ");
 if (user.getCity() != null && !user.getCity().isEmpty()) { 
      out.write("\n");
      out.write("          <div class=\"info-row\">\n");
      out.write("            <span class=\"info-label\">City</span>\n");
      out.write("            <span class=\"info-value\">\n");
      out.write("              ");
      out.print( user.getCity() );
      out.write(',');
      out.write(' ');
      out.print( user.getState() );
      out.write(' ');
      out.write('—');
      out.write(' ');
      out.print( user.getPincode() );
      out.write("\n");
      out.write("            </span>\n");
      out.write("          </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      ");
 if ("PLACED".equalsIgnoreCase(order.getStatus())) { 
      out.write("\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order?action=cancelOrder&orderId=");
      out.print( order.getId() );
      out.write("\"\n");
      out.write("           id=\"cancelBtn\"\n");
      out.write("           style=\"\n");
      out.write("             display:block;\n");
      out.write("             width:100%;\n");
      out.write("             padding:13px;\n");
      out.write("             margin-bottom:12px;\n");
      out.write("             background:transparent;\n");
      out.write("             color:#e57373;\n");
      out.write("             border:1px solid #c0392b;\n");
      out.write("             border-radius:2px;\n");
      out.write("             font-family:'Barlow',sans-serif;\n");
      out.write("             font-size:10px;\n");
      out.write("             font-weight:500;\n");
      out.write("             letter-spacing:2px;\n");
      out.write("             text-transform:uppercase;\n");
      out.write("             text-align:center;\n");
      out.write("             text-decoration:none;\n");
      out.write("             transition:background 0.2s,color 0.2s;\n");
      out.write("           \"\n");
      out.write("           onmouseover=\"this.style.background='rgba(192,57,43,0.1)'\"\n");
      out.write("           onmouseout=\"this.style.background='transparent'\"\n");
      out.write("           onclick=\"cancelOrder(event, '");
      out.print( order.getId() );
      out.write("')\">\n");
      out.write("          &#10005; &nbsp;Cancel Order\n");
      out.write("        </a>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order?action=myOrders\" class=\"btn-back\">\n");
      out.write("        &#8592; &nbsp;Back to Orders\n");
      out.write("      </a>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <footer class=\"site-footer\">\n");
      out.write("    <div class=\"footer-logo\">FASHION<span>.</span></div>\n");
      out.write("    <p class=\"footer-note\">&copy; 2025 FashionStore. All rights reserved.</p>\n");
      out.write("  </footer>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/toast.js\"></script>\n");
      out.write("<!-- Cancel Confirmation Modal -->\n");
      out.write("<div id=\"cancelModal\" style=\"\n");
      out.write("  display:none;position:fixed;inset:0;z-index:9999;\n");
      out.write("  background:rgba(0,0,0,0.75);backdrop-filter:blur(4px);\n");
      out.write("  align-items:center;justify-content:center;\n");
      out.write("\">\n");
      out.write("  <div style=\"\n");
      out.write("    background:#111;border:1px solid #2e2e2e;border-radius:4px;\n");
      out.write("    padding:36px;max-width:380px;width:90%;position:relative;\n");
      out.write("    box-shadow:0 24px 64px rgba(0,0,0,0.8);\n");
      out.write("  \">\n");
      out.write("    <div style=\"position:absolute;top:0;left:0;right:0;height:2px;background:#c0392b;border-radius:4px 4px 0 0;\"></div>\n");
      out.write("    <div style=\"text-align:center;margin-bottom:16px;\">\n");
      out.write("      <div style=\"width:52px;height:52px;background:rgba(192,57,43,0.1);border:1px solid #c0392b;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;font-size:20px;color:#e57373;\">✕</div>\n");
      out.write("    </div>\n");
      out.write("    <h3 style=\"font-family:'Playfair Display',serif;font-size:22px;font-weight:700;color:#f5f5f0;text-align:center;margin-bottom:8px;\">Cancel Order?</h3>\n");
      out.write("    <p style=\"font-size:13px;color:#777;text-align:center;margin-bottom:28px;line-height:1.6;\">This action cannot be undone. Your order will be marked as cancelled.</p>\n");
      out.write("    <div style=\"display:flex;gap:12px;\">\n");
      out.write("      <button onclick=\"document.getElementById('cancelModal').style.display='none';document.body.style.overflow='';\" style=\"\n");
      out.write("        flex:1;padding:12px;background:transparent;color:#999;border:1px solid #2e2e2e;\n");
      out.write("        border-radius:2px;font-family:'Barlow',sans-serif;font-size:11px;font-weight:500;\n");
      out.write("        letter-spacing:2px;text-transform:uppercase;cursor:pointer;\n");
      out.write("      \">Keep Order</button>\n");
      out.write("      <a id=\"cancelConfirmBtn\" href=\"#\" style=\"\n");
      out.write("        flex:1;padding:12px;background:#c0392b;color:#fff;border:none;border-radius:2px;\n");
      out.write("        font-family:'Barlow',sans-serif;font-size:11px;font-weight:600;\n");
      out.write("        letter-spacing:2px;text-transform:uppercase;cursor:pointer;\n");
      out.write("        text-align:center;text-decoration:none;display:flex;align-items:center;justify-content:center;\n");
      out.write("      \">Yes, Cancel</a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  function cancelOrder(e, orderId) {\n");
      out.write("    e.preventDefault();\n");
      out.write("    const modal = document.getElementById('cancelModal');\n");
      out.write("    const confirmBtn = document.getElementById('cancelConfirmBtn');\n");
      out.write("    confirmBtn.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order?action=cancelOrder&orderId=' + orderId;\n");
      out.write("    modal.style.display = 'flex';\n");
      out.write("    document.body.style.overflow = 'hidden';\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  // Close on backdrop click\n");
      out.write("  document.getElementById('cancelModal').addEventListener('click', function(e) {\n");
      out.write("    if (e.target === this) {\n");
      out.write("      this.style.display = 'none';\n");
      out.write("      document.body.style.overflow = '';\n");
      out.write("    }\n");
      out.write("  });\n");
      out.write("\n");
      out.write("  // Close on Escape\n");
      out.write("  document.addEventListener('keydown', function(e) {\n");
      out.write("    if (e.key === 'Escape') {\n");
      out.write("      document.getElementById('cancelModal').style.display = 'none';\n");
      out.write("      document.body.style.overflow = '';\n");
      out.write("    }\n");
      out.write("  });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
