/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-05-29 07:39:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.fashionstore.model.Product;
import com.fashionstore.model.User;

public final class products_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.fashionstore.model.Product");
    _jspx_imports_classes.add("com.fashionstore.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    List<Product> products = (List<Product>) request.getAttribute("products");
    User user = (User) session.getAttribute("user");
    int cartCount = request.getAttribute("cartCount") != null ? (int) request.getAttribute("cartCount") : 0;
    String keyword = request.getParameter("search");
    String categoryId = request.getParameter("categoryId");
    if (keyword == null) keyword = "";
    if (categoryId == null) categoryId = "";
    int productCount = (products != null) ? products.size() : 0;
    String activeLabel = "All Products";
    if ("1".equals(categoryId)) activeLabel = "Men";
    else if ("2".equals(categoryId)) activeLabel = "Women";
    else if ("4".equals(categoryId)) activeLabel = "Kids";
    else if (!keyword.isEmpty()) activeLabel = "Search: " + keyword;
    String sortBy = request.getAttribute("sortBy") != null ? (String) request.getAttribute("sortBy") : "newest";

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>");
      out.print( activeLabel );
      out.write(" — FashionStore</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/products.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/toast.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"top-nav\">\n");
      out.write("  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" class=\"nav-logo\">FASHION<span>.</span></a>\n");
      out.write("  <form class=\"nav-search-form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" method=\"get\">\n");
      out.write("    <input class=\"nav-search-input\" type=\"text\" name=\"search\" placeholder=\"Search products...\" value=\"");
      out.print( keyword );
      out.write("\" autocomplete=\"off\">\n");
      out.write("    <button class=\"nav-search-btn\" type=\"submit\">&#8981;</button>\n");
      out.write("  </form>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    ");
 if (user != null) { 
      out.write("\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=profile\">");
      out.print( user.getName().split(" ")[0] );
      out.write("</a></li>\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order?action=myOrders\">Orders</a></li>\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart\" class=\"nav-cart\">Cart");
 if (cartCount > 0) { 
      out.write("<span class=\"nav-cart-badge\">");
      out.print( cartCount );
      out.write("</span>");
 } 
      out.write("</a></li>\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=logout\">Sign out</a></li>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=login\">Sign in</a></li>\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=register\">Register</a></li>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("<div class=\"page-body\">\n");
      out.write("  <div class=\"hero-strip\">\n");
      out.write("    <div class=\"hero-text\">\n");
      out.write("      <p class=\"hero-eyebrow\">New Collection · 2026</p>\n");
      out.write("      <h1 class=\"hero-title\">");
      out.print( activeLabel );
      out.write("</h1>\n");
      out.write("      <p class=\"hero-count\">");
      out.print( productCount );
      out.write(' ');
      out.print( productCount == 1 ? "piece" : "pieces" );
      out.write("</p>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"filter-bar\">\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"filter-link ");
      out.print( categoryId.isEmpty() && keyword.isEmpty() ? "active" : "" );
      out.write("\">All</a>\n");
      out.write("    <div class=\"filter-divider\"></div>\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?categoryId=1\" class=\"filter-link ");
      out.print( "1".equals(categoryId) ? "active" : "" );
      out.write("\">Men</a>\n");
      out.write("    <div class=\"filter-divider\"></div>\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?categoryId=2\" class=\"filter-link ");
      out.print( "2".equals(categoryId) ? "active" : "" );
      out.write("\">Women</a>\n");
      out.write("    <div class=\"filter-divider\"></div>\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?categoryId=4\" class=\"filter-link ");
      out.print( "4".equals(categoryId) ? "active" : "" );
      out.write("\">Kids</a>\n");
      out.write("    ");
 if (!keyword.isEmpty()) { 
      out.write("\n");
      out.write("      <div class=\"filter-divider\"></div>\n");
      out.write("      <span class=\"filter-link active\">&ldquo;");
      out.print( keyword );
      out.write("&rdquo;&nbsp;<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" style=\"color:var(--muted);font-size:10px;text-decoration:none;\">✕</a></span>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Sort dropdown -->\n");
      out.write("    <div style=\"margin-left:auto; display:flex; align-items:center; padding-right:24px;\">\n");
      out.write("      <form id=\"sortForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" method=\"get\" style=\"display:flex;align-items:center;gap:10px;\">\n");
      out.write("        ");
 if (!categoryId.isEmpty()) { 
      out.write("\n");
      out.write("          <input type=\"hidden\" name=\"categoryId\" value=\"");
      out.print( categoryId );
      out.write("\">\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        ");
 if (!keyword.isEmpty()) { 
      out.write("\n");
      out.write("          <input type=\"hidden\" name=\"search\" value=\"");
      out.print( keyword );
      out.write("\">\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <label style=\"font-size:10px;letter-spacing:2px;text-transform:uppercase;color:var(--muted);font-weight:500;\">Sort</label>\n");
      out.write("        <select name=\"sort\" onchange=\"document.getElementById('sortForm').submit()\"\n");
      out.write("                style=\"background:var(--graphite);border:1px solid var(--border);color:var(--light);font-family:'Barlow',sans-serif;font-size:11px;padding:6px 12px;border-radius:2px;cursor:pointer;outline:none;\">\n");
      out.write("          <option value=\"newest\"     ");
      out.print( "newest".equals(sortBy)     ? "selected" : "" );
      out.write(">Newest</option>\n");
      out.write("          <option value=\"price_asc\"  ");
      out.print( "price_asc".equals(sortBy)  ? "selected" : "" );
      out.write(">Price: Low to High</option>\n");
      out.write("          <option value=\"price_desc\" ");
      out.print( "price_desc".equals(sortBy) ? "selected" : "" );
      out.write(">Price: High to Low</option>\n");
      out.write("          <option value=\"name_asc\"   ");
      out.print( "name_asc".equals(sortBy)   ? "selected" : "" );
      out.write(">Name: A to Z</option>\n");
      out.write("          <option value=\"name_desc\"  ");
      out.print( "name_desc".equals(sortBy)  ? "selected" : "" );
      out.write(">Name: Z to A</option>\n");
      out.write("        </select>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"shop-layout\">\n");
      out.write("    <div class=\"product-grid\">\n");
      out.write("      ");
 if (products != null && !products.isEmpty()) { for (Product p : products) { 
      out.write("\n");
      out.write("        <div class=\"product-card\">\n");
      out.write("          <div class=\"card-img-wrap\">\n");
      out.write("            ");
 if (p.getImageUrl() != null && !p.getImageUrl().isEmpty()) { 
      out.write("\n");
      out.write("              <img class=\"product-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.print( p.getImageUrl() );
      out.write("\" alt=\"");
      out.print( p.getName() );
      out.write("\" loading=\"lazy\">\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("              <div class=\"product-img-placeholder\">\n");
      out.write("                <svg width=\"40\" height=\"40\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\"><rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\"/><circle cx=\"8.5\" cy=\"8.5\" r=\"1.5\"/><polyline points=\"21,15 16,10 5,21\"/></svg>\n");
      out.write("              </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <div class=\"card-body\">\n");
      out.write("            <p class=\"product-category-tag\">");
      out.print( "1".equals(String.valueOf(p.getCategoryId())) ? "Men" : "2".equals(String.valueOf(p.getCategoryId())) ? "Women" : "Kids" );
      out.write("</p>\n");
      out.write("            <h3 class=\"product-name\">");
      out.print( p.getName() );
      out.write("</h3>\n");
      out.write("            <p class=\"product-price\">&#8377;");
      out.print( String.format("%.0f", p.getPrice()) );
      out.write("</p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"card-actions\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product-details?id=");
      out.print( p.getId() );
      out.write("\" class=\"btn-view\">View Details</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      ");
 } } else { 
      out.write("\n");
      out.write("        <div class=\"empty-state\">\n");
      out.write("          <div class=\"empty-state-icon\"><svg width=\"64\" height=\"64\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"0.8\"><circle cx=\"11\" cy=\"11\" r=\"8\"/><line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\"/></svg></div>\n");
      out.write("          <h3>Nothing found</h3>\n");
      out.write("          <p>We couldn't find any products matching your criteria.</p>\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\">Browse all products</a>\n");
      out.write("        </div>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <footer class=\"site-footer\">\n");
      out.write("    <div class=\"footer-logo\">FASHION<span>.</span></div>\n");
      out.write("    <p class=\"footer-note\">&copy; 2025 FashionStore. All rights reserved.</p>\n");
      out.write("  </footer>\n");
      out.write("</div>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/toast.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
