/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-05-29 05:50:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.fashionstore.model.Product;
import com.fashionstore.model.ProductVariant;
import com.fashionstore.model.User;

public final class product_002ddetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.fashionstore.model.Product");
    _jspx_imports_classes.add("com.fashionstore.model.User");
    _jspx_imports_classes.add("com.fashionstore.model.ProductVariant");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Product product = (Product) request.getAttribute("product");

    if(product == null){
        out.println("Product not found.");
        return;
    }

    List<ProductVariant> variants =
            (List<ProductVariant>) request.getAttribute("variants");

    List<Product> related =
            (List<Product>) request.getAttribute("related");

    String categoryName =
            (String) request.getAttribute("categoryName");

    User user = (User) session.getAttribute("user");

    int cartCount = request.getAttribute("cartCount") != null
            ? (int) request.getAttribute("cartCount")
            : 0;

    boolean hasVariants =
            variants != null && !variants.isEmpty();

    boolean hasStock = false;

    if (hasVariants) {
        for (ProductVariant v : variants) {
            if (v.getStock() > 0) {
                hasStock = true;
                break;
            }
        }
    }

    boolean cartError =
            "cart".equals(request.getParameter("error"));

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("    <title>");
      out.print( product.getName() );
      out.write(" — FashionStore</title>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\"\n");
      out.write("          href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/product-detail.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\"\n");
      out.write("          href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/toast.css\">\n");
      out.write("\n");
      out.write("    ");
 if ("true".equals(request.getParameter("added"))) { 
      out.write("\n");
      out.write("        <meta name=\"toast-message\"\n");
      out.write("              content=\"Added to cart!\"\n");
      out.write("              data-type=\"success\"\n");
      out.write("              data-sub=\"View your cart to checkout\">\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    ");
 if (cartError) { 
      out.write("\n");
      out.write("        <meta name=\"toast-message\"\n");
      out.write("              content=\"Failed to add to cart\"\n");
      out.write("              data-type=\"error\"\n");
      out.write("              data-sub=\"Please try again\">\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- NAVBAR -->\n");
      out.write("<nav class=\"top-nav\">\n");
      out.write("\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\"\n");
      out.write("       class=\"nav-logo\">\n");
      out.write("        FASHION<span>.</span>\n");
      out.write("    </a>\n");
      out.write("\n");
      out.write("    <ul class=\"nav-links\">\n");
      out.write("\n");
      out.write("        ");
 if (user != null) { 
      out.write("\n");
      out.write("\n");
      out.write("            <li>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=profile\">\n");
      out.write("                    ");
      out.print( user.getName().split(" ")[0] );
      out.write("\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("            <li>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order?action=myOrders\">\n");
      out.write("                    Orders\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("            <li>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart\"\n");
      out.write("                   class=\"nav-cart\">\n");
      out.write("\n");
      out.write("                    Cart\n");
      out.write("\n");
      out.write("                    ");
 if (cartCount > 0) { 
      out.write("\n");
      out.write("                        <span class=\"nav-cart-badge\">\n");
      out.write("                            ");
      out.print( cartCount );
      out.write("\n");
      out.write("                        </span>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("            <li>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=logout\">\n");
      out.write("                    Sign out\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("\n");
      out.write("            <li>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=login\">\n");
      out.write("                    Sign in\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("            <li>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=register\">\n");
      out.write("                    Register\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    </ul>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"page-body\">\n");
      out.write("\n");
      out.write("    <!-- BREADCRUMB -->\n");
      out.write("    <div class=\"breadcrumb\">\n");
      out.write("\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\">\n");
      out.write("            All Products\n");
      out.write("        </a>\n");
      out.write("\n");
      out.write("        <span class=\"breadcrumb-sep\">&#8250;</span>\n");
      out.write("\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?categoryId=");
      out.print( product.getCategoryId() );
      out.write("\">\n");
      out.write("            ");
      out.print( categoryName );
      out.write("\n");
      out.write("        </a>\n");
      out.write("\n");
      out.write("        <span class=\"breadcrumb-sep\">&#8250;</span>\n");
      out.write("\n");
      out.write("        <span class=\"breadcrumb-current\">\n");
      out.write("            ");
      out.print( product.getName() );
      out.write("\n");
      out.write("        </span>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- PRODUCT SECTION -->\n");
      out.write("    <div class=\"product-section\">\n");
      out.write("\n");
      out.write("        <!-- IMAGE -->\n");
      out.write("        <div class=\"product-image-wrap\">\n");
      out.write("\n");
      out.write("            <span class=\"img-category-tag\">\n");
      out.write("                ");
      out.print( categoryName );
      out.write("\n");
      out.write("            </span>\n");
      out.write("\n");
      out.write("            ");
 if (product.getImageUrl() != null &&
                   !product.getImageUrl().isEmpty()) { 
      out.write("\n");
      out.write("\n");
      out.write("                <img\n");
      out.write("                    src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.print( product.getImageUrl() );
      out.write("\"\n");
      out.write("                    alt=\"");
      out.print( product.getName() );
      out.write("\">\n");
      out.write("\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("\n");
      out.write("                <div class=\"product-image-placeholder\">\n");
      out.write("\n");
      out.write("                    <svg width=\"64\"\n");
      out.write("                         height=\"64\"\n");
      out.write("                         viewBox=\"0 0 24 24\"\n");
      out.write("                         fill=\"none\"\n");
      out.write("                         stroke=\"currentColor\"\n");
      out.write("                         stroke-width=\"0.8\">\n");
      out.write("\n");
      out.write("                        <rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\"/>\n");
      out.write("                        <circle cx=\"8.5\" cy=\"8.5\" r=\"1.5\"/>\n");
      out.write("                        <polyline points=\"21,15 16,10 5,21\"/>\n");
      out.write("\n");
      out.write("                    </svg>\n");
      out.write("\n");
      out.write("                    <span style=\"font-size:12px;letter-spacing:1px;margin-top:8px;\">\n");
      out.write("                        No image available\n");
      out.write("                    </span>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- PRODUCT INFO -->\n");
      out.write("        <div class=\"product-info\">\n");
      out.write("\n");
      out.write("            <p class=\"product-info-eyebrow\">\n");
      out.write("                ");
      out.print( categoryName );
      out.write(" · FashionStore\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("            <h1 class=\"product-info-name\">\n");
      out.write("                ");
      out.print( product.getName() );
      out.write("\n");
      out.write("            </h1>\n");
      out.write("\n");
      out.write("            <p class=\"product-info-price\">\n");
      out.write("                &#8377;");
      out.print( String.format("%.0f", product.getPrice()) );
      out.write("\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("            ");
 if (cartError) { 
      out.write("\n");
      out.write("                <div class=\"alert alert-error\">\n");
      out.write("                    Failed to add to cart. Please try again.\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"divider\"></div>\n");
      out.write("\n");
      out.write("            <!-- DESCRIPTION -->\n");
      out.write("            ");
 if (product.getDescription() != null &&
                   !product.getDescription().isEmpty()) { 
      out.write("\n");
      out.write("\n");
      out.write("                <p class=\"product-desc-label\">Description</p>\n");
      out.write("\n");
      out.write("                <p class=\"product-desc-text\">\n");
      out.write("                    ");
      out.print( product.getDescription() );
      out.write("\n");
      out.write("                </p>\n");
      out.write("\n");
      out.write("                <div class=\"divider\"></div>\n");
      out.write("\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <!-- ADD TO CART -->\n");
      out.write("            ");
 if (user != null) { 
      out.write("\n");
      out.write("\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product-details\"\n");
      out.write("                      method=\"post\"\n");
      out.write("                      id=\"cartForm\">\n");
      out.write("\n");
      out.write("                    <input type=\"hidden\"\n");
      out.write("                           name=\"productId\"\n");
      out.write("                           value=\"");
      out.print( product.getId() );
      out.write("\">\n");
      out.write("\n");
      out.write("                    <input type=\"hidden\"\n");
      out.write("                           name=\"variantId\"\n");
      out.write("                           id=\"selectedVariantId\"\n");
      out.write("                           value=\"\">\n");
      out.write("\n");
      out.write("                    <!-- SIZE -->\n");
      out.write("                    ");
 if (hasVariants) { 
      out.write("\n");
      out.write("\n");
      out.write("                        <div class=\"size-label\">\n");
      out.write("                            Select Size\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"size-grid\">\n");
      out.write("\n");
      out.write("                            ");
 for (ProductVariant v : variants) {

                                boolean outOfStock =
                                        v.getStock() <= 0;
                            
      out.write("\n");
      out.write("\n");
      out.write("                                <input\n");
      out.write("                                        type=\"radio\"\n");
      out.write("                                        class=\"size-option ");
      out.print( outOfStock ? "out-of-stock" : "" );
      out.write("\"\n");
      out.write("                                        name=\"sizeRadio\"\n");
      out.write("                                        id=\"size_");
      out.print( v.getId() );
      out.write("\"\n");
      out.write("                                        value=\"");
      out.print( v.getId() );
      out.write("\"\n");
      out.write("                                        data-stock=\"");
      out.print( v.getStock() );
      out.write("\"\n");
      out.write("                                        ");
      out.print( outOfStock ? "disabled" : "" );
      out.write("\n");
      out.write("                                >\n");
      out.write("\n");
      out.write("                                <label for=\"size_");
      out.print( v.getId() );
      out.write("\">\n");
      out.write("                                    ");
      out.print( v.getSize() );
      out.write("\n");
      out.write("                                </label>\n");
      out.write("\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <p class=\"stock-note\" id=\"stockNote\">\n");
      out.write("                            Select a size to check availability\n");
      out.write("                        </p>\n");
      out.write("\n");
      out.write("                    ");
 } else { 
      out.write("\n");
      out.write("\n");
      out.write("                        <p class=\"stock-note no-stock\">\n");
      out.write("                            No sizes available.\n");
      out.write("                        </p>\n");
      out.write("\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"divider\"></div>\n");
      out.write("\n");
      out.write("                    <!-- QUANTITY -->\n");
      out.write("                    ");
 if (hasStock) { 
      out.write("\n");
      out.write("\n");
      out.write("                        <p class=\"qty-label\">Quantity</p>\n");
      out.write("\n");
      out.write("                        <div class=\"qty-control\"\n");
      out.write("                             style=\"margin-bottom:24px;\">\n");
      out.write("\n");
      out.write("                            <button type=\"button\"\n");
      out.write("                                    class=\"qty-btn\"\n");
      out.write("                                    id=\"qtyMinus\">\n");
      out.write("\n");
      out.write("                                &#8722;\n");
      out.write("\n");
      out.write("                            </button>\n");
      out.write("\n");
      out.write("                            <input type=\"number\"\n");
      out.write("                                   class=\"qty-input\"\n");
      out.write("                                   name=\"quantity\"\n");
      out.write("                                   id=\"qtyInput\"\n");
      out.write("                                   value=\"1\"\n");
      out.write("                                   min=\"1\"\n");
      out.write("                                   max=\"10\"\n");
      out.write("                                   readonly>\n");
      out.write("\n");
      out.write("                            <button type=\"button\"\n");
      out.write("                                    class=\"qty-btn\"\n");
      out.write("                                    id=\"qtyPlus\">\n");
      out.write("\n");
      out.write("                                &#43;\n");
      out.write("\n");
      out.write("                            </button>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                    <button\n");
      out.write("                            type=\"submit\"\n");
      out.write("                            class=\"btn-add-cart\"\n");
      out.write("                            id=\"addCartBtn\"\n");
      out.write("                            ");
      out.print( !hasStock ? "disabled" : "" );
      out.write("\n");
      out.write("                    >\n");
      out.write("\n");
      out.write("                        ");
      out.print( hasStock ? "Add to Cart" : "Out of Stock" );
      out.write("\n");
      out.write("\n");
      out.write("                    </button>\n");
      out.write("\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("\n");
      out.write("                <div class=\"divider\"></div>\n");
      out.write("\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=login\"\n");
      out.write("                   class=\"btn-add-cart\"\n");
      out.write("                   style=\"display:block;text-align:center;text-decoration:none;padding:16px;\">\n");
      out.write("\n");
      out.write("                    Sign in to Add to Cart\n");
      out.write("\n");
      out.write("                </a>\n");
      out.write("\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- RELATED PRODUCTS -->\n");
      out.write("    ");
 if (related != null && !related.isEmpty()) { 
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"related-section\">\n");
      out.write("\n");
      out.write("            <h2 class=\"related-heading\">\n");
      out.write("                You May Also Like\n");
      out.write("            </h2>\n");
      out.write("\n");
      out.write("            <div class=\"related-grid\">\n");
      out.write("\n");
      out.write("                ");
 for (Product r : related) { 
      out.write("\n");
      out.write("\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product-details?id=");
      out.print( r.getId() );
      out.write("\"\n");
      out.write("                       class=\"related-card\">\n");
      out.write("\n");
      out.write("                        <div class=\"related-img-wrap\">\n");
      out.write("\n");
      out.write("                            ");
 if (r.getImageUrl() != null &&
                                   !r.getImageUrl().isEmpty()) { 
      out.write("\n");
      out.write("\n");
      out.write("                                <img class=\"related-img\"\n");
      out.write("                                     src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.print( r.getImageUrl() );
      out.write("\"\n");
      out.write("                                     alt=\"");
      out.print( r.getName() );
      out.write("\">\n");
      out.write("\n");
      out.write("                            ");
 } else { 
      out.write("\n");
      out.write("\n");
      out.write("                                <div class=\"related-img-placeholder\">\n");
      out.write("                                    &#9900;\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"related-body\">\n");
      out.write("\n");
      out.write("                            <p class=\"related-name\">\n");
      out.write("                                ");
      out.print( r.getName() );
      out.write("\n");
      out.write("                            </p>\n");
      out.write("\n");
      out.write("                            <p class=\"related-price\">\n");
      out.write("                                &#8377;");
      out.print( String.format("%.0f", r.getPrice()) );
      out.write("\n");
      out.write("                            </p>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                    </a>\n");
      out.write("\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <!-- FOOTER -->\n");
      out.write("    <footer class=\"site-footer\">\n");
      out.write("\n");
      out.write("        <div class=\"footer-logo\">\n");
      out.write("            FASHION<span>.</span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <p class=\"footer-note\">\n");
      out.write("            &copy; 2025 FashionStore. All rights reserved.\n");
      out.write("        </p>\n");
      out.write("\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/toast.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("    const sizeRadios =\n");
      out.write("        document.querySelectorAll('.size-option:not(.out-of-stock)');\n");
      out.write("\n");
      out.write("    const variantInput =\n");
      out.write("        document.getElementById('selectedVariantId');\n");
      out.write("\n");
      out.write("    const stockNote =\n");
      out.write("        document.getElementById('stockNote');\n");
      out.write("\n");
      out.write("    const addCartBtn =\n");
      out.write("        document.getElementById('addCartBtn');\n");
      out.write("\n");
      out.write("    sizeRadios.forEach(radio => {\n");
      out.write("\n");
      out.write("        radio.addEventListener('change', () => {\n");
      out.write("\n");
      out.write("            const stock =\n");
      out.write("                parseInt(radio.dataset.stock);\n");
      out.write("\n");
      out.write("            variantInput.value = radio.value;\n");
      out.write("\n");
      out.write("            if (stockNote) {\n");
      out.write("\n");
      out.write("                if (stock > 0) {\n");
      out.write("\n");
      out.write("                    stockNote.textContent =\n");
      out.write("                        \"In stock\";\n");
      out.write("\n");
      out.write("                    stockNote.className =\n");
      out.write("                        \"stock-note in-stock\";\n");
      out.write("\n");
      out.write("                } else {\n");
      out.write("\n");
      out.write("                    stockNote.textContent =\n");
      out.write("                        \"Out of stock\";\n");
      out.write("\n");
      out.write("                    stockNote.className =\n");
      out.write("                        \"stock-note no-stock\";\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            if (addCartBtn) {\n");
      out.write("\n");
      out.write("                addCartBtn.disabled = false;\n");
      out.write("\n");
      out.write("                addCartBtn.textContent =\n");
      out.write("                    \"Add to Cart\";\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    const qtyInput =\n");
      out.write("        document.getElementById('qtyInput');\n");
      out.write("\n");
      out.write("    const qtyMinus =\n");
      out.write("        document.getElementById('qtyMinus');\n");
      out.write("\n");
      out.write("    const qtyPlus =\n");
      out.write("        document.getElementById('qtyPlus');\n");
      out.write("\n");
      out.write("    if (qtyMinus && qtyPlus && qtyInput) {\n");
      out.write("\n");
      out.write("        qtyMinus.addEventListener('click', () => {\n");
      out.write("\n");
      out.write("            const v = parseInt(qtyInput.value);\n");
      out.write("\n");
      out.write("            if (v > 1) {\n");
      out.write("                qtyInput.value = v - 1;\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        qtyPlus.addEventListener('click', () => {\n");
      out.write("\n");
      out.write("            const v = parseInt(qtyInput.value);\n");
      out.write("\n");
      out.write("            if (v < 10) {\n");
      out.write("                qtyInput.value = v + 1;\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    const cartForm =\n");
      out.write("        document.getElementById('cartForm');\n");
      out.write("\n");
      out.write("    if (cartForm) {\n");
      out.write("\n");
      out.write("        cartForm.addEventListener('submit', e => {\n");
      out.write("\n");
      out.write("            if (!variantInput.value) {\n");
      out.write("\n");
      out.write("                e.preventDefault();\n");
      out.write("\n");
      out.write("                if (stockNote) {\n");
      out.write("\n");
      out.write("                    stockNote.textContent =\n");
      out.write("                        \"Please select a size first.\";\n");
      out.write("\n");
      out.write("                    stockNote.className =\n");
      out.write("                        \"stock-note no-stock\";\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
