/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2026-05-29 05:56:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.fashionstore.model.User;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("com.fashionstore.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    User user = (User) request.getAttribute("user");
    if (user == null) { response.sendRedirect(request.getContextPath() + "/user?action=login"); return; }
    String[] nameParts = user.getName().trim().split("\\s+");
    String initials = nameParts.length >= 2
        ? String.valueOf(nameParts[0].charAt(0)) + String.valueOf(nameParts[nameParts.length-1].charAt(0))
        : String.valueOf(nameParts[0].charAt(0));
    initials = initials.toUpperCase();
    int cartCount = request.getAttribute("cartCount") != null ? (int) request.getAttribute("cartCount") : 0;
    boolean hasSuccess = request.getAttribute("success") != null;
    boolean hasError   = request.getAttribute("error") != null;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>My Account — FashionStore</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/auth.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/toast.css\">\n");
      out.write("  ");
 if (hasSuccess) { 
      out.write("\n");
      out.write("    <meta name=\"toast-message\" content=\"Profile updated successfully!\" data-type=\"success\">\n");
      out.write("  ");
 } 
      out.write('\n');
      out.write(' ');
      out.write(' ');
 if (hasError) { 
      out.write("\n");
      out.write("    <meta name=\"toast-message\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" data-type=\"error\">\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"top-nav\">\n");
      out.write("  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"nav-logo\">FASHION<span>.</span></a>\n");
      out.write("  <ul class=\"nav-links\">\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\">Shop</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order?action=myOrders\">Orders</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=profile\" class=\"active\">Account</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart\" class=\"nav-cart\">Cart");
 if (cartCount > 0) { 
      out.write("<span class=\"nav-cart-badge\">");
      out.print( cartCount );
      out.write("</span>");
 } 
      out.write("</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=logout\">Sign out</a></li>\n");
      out.write("  </ul>\n");
      out.write("</nav>\n");
      out.write("<div class=\"main-with-nav\">\n");
      out.write("  <div class=\"profile-wrapper\">\n");
      out.write("    <div class=\"profile-header\">\n");
      out.write("      <div class=\"profile-header-left\">\n");
      out.write("        <p class=\"eyebrow\">My Account</p>\n");
      out.write("        <h1>");
      out.print( user.getName() );
      out.write("</h1>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"profile-avatar\">");
      out.print( initials );
      out.write("</div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user\" method=\"post\" novalidate>\n");
      out.write("      <input type=\"hidden\" name=\"action\" value=\"updateProfile\">\n");
      out.write("      <div class=\"profile-grid\">\n");
      out.write("        <div class=\"profile-card\">\n");
      out.write("          <p class=\"profile-card-title\">Personal Information</p>\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label for=\"name\">Full name</label>\n");
      out.write("            <input type=\"text\" id=\"name\" name=\"name\" value=\"");
      out.print( user.getName() );
      out.write("\" required>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label for=\"email\">Email address</label>\n");
      out.write("            <input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.print( user.getEmail() );
      out.write("\" required>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label for=\"password\">New password</label>\n");
      out.write("            <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Leave blank to keep current\" autocomplete=\"new-password\">\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"profile-card\">\n");
      out.write("          <p class=\"profile-card-title\">Delivery Address</p>\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label for=\"addressLine\">Street address</label>\n");
      out.write("            <input type=\"text\" id=\"addressLine\" name=\"addressLine\" value=\"");
      out.print( user.getAddressLine() != null ? user.getAddressLine() : "" );
      out.write("\" placeholder=\"123, MG Road\">\n");
      out.write("          </div>\n");
      out.write("          <div class=\"form-row\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"city\">City</label>\n");
      out.write("              <input type=\"text\" id=\"city\" name=\"city\" value=\"");
      out.print( user.getCity() != null ? user.getCity() : "" );
      out.write("\" placeholder=\"Bengaluru\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"state\">State</label>\n");
      out.write("              <input type=\"text\" id=\"state\" name=\"state\" value=\"");
      out.print( user.getState() != null ? user.getState() : "" );
      out.write("\" placeholder=\"Karnataka\">\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label for=\"pincode\">Pincode</label>\n");
      out.write("            <input type=\"text\" id=\"pincode\" name=\"pincode\" value=\"");
      out.print( user.getPincode() != null ? user.getPincode() : "" );
      out.write("\" placeholder=\"560001\" maxlength=\"6\">\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"profile-card profile-card--full\" style=\"padding:24px 32px;display:flex;align-items:center;justify-content:space-between;\">\n");
      out.write("          <p style=\"font-size:12px;color:var(--muted);\">Changes saved here update your account and delivery address.</p>\n");
      out.write("          <button type=\"submit\" class=\"btn-primary\" style=\"width:auto;padding:14px 40px;white-space:nowrap;\">Save Changes</button>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <div class=\"divider\"></div>\n");
      out.write("    <div style=\"display:flex;gap:16px;flex-wrap:wrap;\">\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order?action=myOrders\" class=\"btn-secondary\" style=\"width:auto;padding:12px 32px;\">View Orders</a>\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products\" class=\"btn-secondary\" style=\"width:auto;padding:12px 32px;\">Continue Shopping</a>\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user?action=logout\" class=\"btn-secondary\" style=\"width:auto;padding:12px 32px;border-color:var(--danger);color:var(--danger);\">Sign Out</a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/toast.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
